#!python3
import os
li=os.listdir()
for i in li:
    n,t = os.path.splitext(i)
    if (t.lower() in [".mkv",".mp4",".mts",".flv",".avi"]) and os.path.isfile(i):
        os.system('ffmpeg -i "{}" -vcodec prores -profile:v 3 -acodec pcm_s16le "{}.mov"'.format(i,n))
